### ISSUE TITLE
Cannot download datasets

### ISSUE THREAD

**Issue by yohohohoho** [filipradenovic/cnnimageretrieval-pytorch#42] opened 2019-06-18 07:57 UTC
It seems that all the links have failed. Are there any other links available?

**Comment by filipradenovic** [comment] 2019-06-24 11:29
We haven't noticed any problem with the download of datasets at this point. Can you try again?

**Comment by filipradenovic** [comment] 2019-06-24 11:30
#
Duplicate of #36

**Comment by yohohohoho** [comment] 2019-06-29 14:35
> We haven't noticed any problem with the download of datasets at this point. Can you try again?
> 
> Duplicate of #36

Thank you. I downloaded the entire data set after changing the VPN.

**Closed** 2019-07-02 16:53 UTC
Labels: duplicate
