### ISSUE TITLE
How to prepare my dataset for training? 

### ISSUE THREAD

**Issue by HLH13297997663** [filipradenovic/cnnimageretrieval-pytorch#43] opened 2019-08-11 13:57 UTC
Are there some scripts to generate the dataset？

**Comment by RYYAI** [comment] 2019-09-03 02:11
+1

**Comment by filipradenovic** [comment] 2019-09-13 22:12
No, but the dataset structure is simple. Take a look at issue #27 for more details.

**Comment by filipradenovic** [comment] 2019-09-13 22:12
Duplicate of #27.

**Closed by filipradenovic** 2019-09-13 22:12 UTC
